const SIGN_UP_USER = 'SIGN_UP_USER'
const ACTIVATE_SIGN_UP = 'ACTIVATE_SIGN_UP'
const SIGN_IN_USER = 'SIGN_IN_USER'
const GET_USER_INFO = 'GET_USER_INFO'
const SET_USER = 'SET_USER'

export { 
    SIGN_UP_USER,
    ACTIVATE_SIGN_UP,
    SIGN_IN_USER,
    GET_USER_INFO,
    SET_USER
 }